spring:
  application:
    name: Space
  jpa:
    hibernate:
      ddl-auto: update
  #PostgreSQL datasource credentials
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "${DB_URL}"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
